name: Práctico 01

on:
  push:
    branches: "**1**"

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Pytest
        run: pip install pytest

      - name: Run Tests
        run: pytest practico_01/practico_01_test.py
