name: Práctico 01

on:
  push:
    branches: "**1**"

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Dependencies
        run: pip install pytest flake8 hypothesis

      - name: Run Tests
        run: pytest practico_01/practico_01_test.py

      - name: Test Style
        run: flake8 practico_01 --count --max-complexity=10 --max-line-length=130 --ignore=E266,F401,E402 --statistics --show-source
